### ISSUE TITLE
Where is PASCA-V1 (V2, V3)

### ISSUE THREAD

**Issue by talentedx** [PKU-DAIR/SGL#2]
Hi, Your paper is really interesting, and I try to retype this code and find that PASCA-V1(V2, V3) are not included in this respority. From this code, we know that SGAP is a fundamental framework of this paper, and SGC is constructed based on this framework, am I right?

**Comment by zwt233** [comment]
>  From this code, we know that SGAP is a fundamental framework of this paper, and SGC is constructed based on this framework, am I right?

Yes, we adopt the scalable design paradigm (SGAP) in our GNN architecture design. Based on SGAP, we have implemented many scalable GNNs (including SGC) in [https://github.com/PKU-DAIR/SGL/tree/main/sgl/models](https://github.com/PKU-DAIR/SGL/tree/main/sgl/models). 
Besides, PASCA-V1(V2, V3) are searched by our system with the multiple objectives (i.e., predictive accuracy and inference time), and we will add the support of these three scalable models ASAP.

**Comment by talentedx** [comment]
> > From this code, we know that SGAP is a fundamental framework of this paper, and SGC is constructed based on this framework, am I right?
> 
> Yes, we adopt the scalable design paradigm (SGAP) in our GNN architecture design. Based on SGAP, we have implemented many scalable GNNs (including SGC) in https://github.com/PKU-DAIR/SGL/tree/main/sgl/models. Besides, PASCA-V1(V2, V3) are searched by our system with the multiple objectives (i.e., predictive accuracy and inference time), and we will add the support of these three scalable models ASAP.

OK, I am looking forward to the updated SGL including PASCA-V1, V2, V3.

**Comment by zwt233** [comment]
> > > From this code, we know that SGAP is a fundamental framework of this paper, and SGC is constructed based on this framework, am I right?
> > 
> > 
> > Yes, we adopt the scalable design paradigm (SGAP) in our GNN architecture design. Based on SGAP, we have implemented many scalable GNNs (including SGC) in https://github.com/PKU-DAIR/SGL/tree/main/sgl/models. Besides, PASCA-V1(V2, V3) are searched by our system with the multiple objectives (i.e., predictive accuracy and inference time), and we will add the support of these three scalable models ASAP.
> 
> OK, I am looking forward to the updated SGL including PASCA-V1, V2, V3.

Thanks for your attention! Implementing scalable GNNs with SGL is quite simple with our pre-defined operators, and we will continuously add more scalable GNN models for both homogeneous and heterogeneous graphs.
